name: Deploy Frontend to VPN Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  frontend_dir: "/home/moniyom/kw1_BingChilling_Frontend/"
  compose_file: "/home/moniyom/kw1_BingChilling_Infrastructure/compose.yaml"
jobs:
  deploy:
    runs-on: linux
    steps:
      - name: Run Deployment Script
        run: |
          # Enable "exit on error" behavior
          set -e

          # Navigate to the frontend directory
          cd ${{ vars.frontend_dir }}  # Replace with the actual directory path

          # Pull the latest changes from the repository
          git pull

          # Start the Docker services defined in the specified compose file
          docker compose -f ${{ vars.compose_file }} up -d  # Replace with the actual compose file path

          # Provide feedback that the deployment process has started
          echo "Frontend deployment process initiated."
